### ISSUE TITLE
Unable to Get Grafana Dashboard Working

### ISSUE THREAD

**Issue by netcruiser2k10** [bentasker/tplink_to_influxdb#2]
HI

I am unable to get the grafana dashboard to work when importing the JSON file in to grafana. It keeps coming up with "Failed to upgrade legacy queries Datasource cUQqMpkVk was not found.

when importing the JSON it doesnt ask me to assign a datasource so im inclined to think that it is importing one that is hard wired in to the JSON code. Could you suggest how to fix this or any other sources to look at to fix this.

the database i created within grafana is working and ive logged in to my influxdb v2 and checked that data is being written to it and within the influxdb v2 data explorer there is data there.

Also could you help with advice on how to set the script to keep running and to start automaticaly after restart

Thanks In Advance
![Screenshot 2023-09-19 233229](https://github.com/bentasker/tplink_to_influxdb/assets/104116318/58d6263a-f154-47a2-afb3-7088aaed9069)

**Comment by bentasker** [comment]
Hi,

> It keeps coming up with "Failed to upgrade legacy queries Datasource cUQqMpkVk was not found.

That's odd... that'll be the ID of one of my datasources but it should ask you to select one.

It's possible I forgot to hit the "export for external sharing" toggle, I've just re-exported and commited, could you regrab https://raw.githubusercontent.com/bentasker/tplink_to_influxdb/master/example/grafana_dashboard.json and see whether that works?


> Also could you help with advice on how to set the script to keep running and to start automaticaly after restart

OK, so there are two parts to this.

The first is to configure the script to use [persistent mode](https://projects.bentasker.co.uk/gils_projects/issue/utilities/tp-link-to-influxdb/4.html).

In your config file, make sure there's a `poller` section with something like this in it
```yaml
poller:
    # If true, run in an infinite loop
    persist: true
    # Interval in seconds between runs
    interval: 20
```

If you invoke the script it'll run, then sleep for `interval` seconds, then run again etc.

But, if the script errors (or the box reboots etc etc) it won't start back up.

How you implement that will depend on how you're running the script. If you're using the docker container, it's relatively easy, you just add `--restart=unless-stopped` or `--restart=always` to the command line:

```sh
docker run --rm \
--restart=unless-stopped \
--name="tplink_to_influxdb" \
-v $PWD/config.yml:/config.yml \
bentasker12/tplink_to_influxdb:latest
```

The docker daemon will then start the container at boot and restart it if it exits.

If you're **not** using docker then (assuming this is running on a Linux box) the easiest route is probably going to be to create a Unit file for it to have Systemd take responsibility for it.

In the example, I assume that

- The script is at `/home/ben/programs/tplink_to_influxdb/app/collect.py`
- The config file is `/home/ben/.config/tplink_to_influxdb.yml`
- The user to run as is `ben`

Obviously, adjust those to suit your needs

Create a the unit file (we'll move it to the correct location later) called `tplink_to_influxdb.service`
```ini
[Unit]
Description=TPLink to InfluxDB

[Service]
Environment=CONF_FILE=/home/ben/.config/tplink_to_influxdb.yml
User=ben
ExecStart=/home/ben/programs/tplink_to_influxdb/app/collect.py
Restart=always
KillSignal=SIGQUIT
Type=simple


[Install]
WantedBy=multi-user.target
```

We set `Type` to `simple` because the script doesn't fork to the background - this tells Systemd not to wait for it to fork. `Restart=always` means that Systemd will restart it if it fails.

We can install it as a system service by doing the following
```sh
sudo mv tplink_to_influxdb.service /etc/systemd/system
sudo systemctl daemon-reload
```

It should then just a case of starting and enabling it
```sh
sudo systemctl start tplink_to_influxdb
sudo systemctl enable tplink_to_influxdb
```

**Comment by netcruiser2k10** [comment]
Thanks for taking the time to respond to my problem.

i have used the new dashboard JSON code that you have uploadedm this has worked to the point where it allows me to select the datasource for the dashboard. However ive come across another issue where the dashboard appears not to be displaying the data that is being written to the database bucket on influxdb V2. Looking at the exclaimation marks it comes up with some error. ive uploaded screenshots to show.

I have ensured that the data is being written and the script is running correctly. Ive uploaded screenshots to show data is being written.

Is there something im doing wrong with the actual dashboard config ?

thanks for the help with making the script persistant. ill be making the script persistant when ive got the dashboard working however when i reboot i have to always put in the export CONF_FILE line of code to make the script work would this be sorted once ive done the steps you described for making it persistant ?

Im running it via a ubuntu container on proxmox.

![Screenshot 2023-09-20 142342](https://github.com/bentasker/tplink_to_influxdb/assets/104116318/20f5b00a-46ea-4b3a-81a6-712d1bdd5096)
![Screenshot 2023-09-20 142430](https://github.com/bentasker/tplink_to_influxdb/assets/104116318/642ba8ed-5571-4db9-a9b4-131454503217)
![Screenshot 2023-09-20 142445](https://github.com/bentasker/tplink_to_influxdb/assets/104116318/e55ef702-b5b3-42b6-8d3f-f21469a45eff)
![Screenshot 2023-09-20 142458](https://github.com/bentasker/tplink_to_influxdb/assets/104116318/aa593420-704c-4a78-9ae0-1d20f8d2e414)

**Comment by netcruiser2k10** [comment]
Fantastic the dashboard is now populating most of the fields. However the costs part are not showing anything. Is this configured within the dashboard or this supposed to come from the settingd within the tapo smart plug app ?

![Screenshot 2023-09-20 205249](https://github.com/bentasker/tplink_to_influxdb/assets/104116318/7cac364e-972a-44ac-8e45-4327254b91bf)

Ill keep this ticket open untill ive sorted the persistance and the cost settings, if thats ok ?

Thank you so much for your help, its much appreciated.

**Comment by netcruiser2k10** [comment]
Systemd file created and working perfectly

Thanks again for your help :)
Sorry for asking so many questions

**Comment by bentasker** [comment]
Glad it's working for you!
